# Generated by Django 4.2.2 on 2023-06-17 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='ingredient-images')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Measurements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('base_maxiumum', models.IntegerField()),
                ('unit_down', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='%(class)s_unit_size_down', to='recipes_app.measurements')),
                ('unit_up', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='%(class)s_unit_size_up', to='recipes_app.measurements')),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='recipe-images')),
                ('description', models.CharField(max_length=4000)),
                ('servings', models.IntegerField()),
                ('status', models.CharField(default='private', max_length=10)),
                ('base_yield', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('tag_name', models.CharField(max_length=25, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes_app.recipes')),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes_app.tags')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeSteps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes_app.recipes')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('new_recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_recipe', to='recipes_app.recipes')),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_recipe', to='recipes_app.recipes')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=2000)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes_app.recipes')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ingredient_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipes_app.ingredients')),
                ('measurement_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipes_app.measurements')),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes_app.recipes')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientVendors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=120, unique=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='vendor-images')),
                ('description', models.CharField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ingredient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes_app.ingredients')),
            ],
        ),
    ]
